Fix/creating new menu
bancodobrasil/jamie-ui pull request #26
Opened 2023-08-25 12:19 UTC by eduardacastro

2023-08-25 13:05 UTC, eduardacastro commented
#35

2023-08-28 21:12 UTC, eliasfeijo requested changes
Está muito bom para sua primeira entrega no projeto, mas precisa fazer uns ajustes. Dá uma olhada nos comentários que eu fiz, e me chama quando puder pra eu te ajudar.
Seria bom a gente aproveitar pra escrever uns casos de teste também.

2023-08-28 21:12 UTC, eliasfeijo commented on src/components/Menu/Forms/BasicInfo/FormBasicInfo.tsx
> +  setCheckBoxConditions: (hasConditions: boolean) => void;
Já tinha os states `hasConditions` e `setHasConditions` nas linhas abaixo (26 e 27)... provavelmente você não deve ter visto o checkbox que já estava pronto pq ele só aparece se o ambiente do Jamie estiver configurado para integrar com o FeatWS... me chama para eu te ajudar quando puder.

2023-08-28 21:12 UTC, eliasfeijo commented on src/components/Menu/Forms/BasicInfo/FormBasicInfo.tsx
> -        {renderParameters()}
Aqui é onde o checkbox de conditions e o input dos parameters estavam sendo renderizados (se você olhar esses métodos, vai perceber que tem um `if` verificando se o ambiente está integrado com o featws)...

2023-08-28 21:12 UTC, eliasfeijo commented on src/components/Menu/Forms/BasicInfo/FormBasicInfo.tsx
> +            </Box>
Só precisaria colocar esse trecho de código dentro do método `renderHasConditionsCheckbox` e fazer alguns ajustes... me chama que vai ser mais fácil se eu te explicar diretamente. Tirando esses pontos que comentei, o restante parece estar ok.

2023-08-28 21:12 UTC, eliasfeijo commented on src/pages/Menu/Create/Create.tsx
> +  const [mustCheckBoxConditions, setCheckBoxConditions] = React.useState<boolean>(false);
Mesma coisa...

2023-08-28 21:12 UTC, eliasfeijo commented on src/pages/Menu/Edit/Edit.tsx
> +  const [mustCheckBoxConditions, setCheckBoxConditions] = React.useState<boolean>(false);
Mesma coisa...

2023-09-06 15:28 UTC, eliasfeijo approved these changes
LGTM

2023-09-06 15:28 UTC, merged